### ISSUE TITLE
CSS file not applied

### ISSUE THREAD

**Issue by schucan** [premasagar/cleanslate#27]
First of all: thank you so much for this handy file!

I am trying to do exactly [as you suggest](http://cleanslatecss.com/usage/). 

I can see in the developer console (Chrome) that the `link` element is indeed injected in the `head` section of the HTML host page. Also, the injected `div` has the appropriate `cleanslate` class name.

However, the styles are not applied.

Any issues I should know of? Is this a bug?

**Comment by premasagar** [comment]
In the console. in the Net tab, has the stylesheet loaded correctly? If it
has, could you put a version up on codepen, jsbin or jsfiddle?

-- 
*Prem Rose*
premasagar.com

**Comment by schucan** [comment]
Thank you for your very quick response!

Here's what happens: I use javascript to add the CSS file to the head element. I can see in the developer console of chrome that the "link" element is indeed added. However, the file is not loaded (according to the net tab).

Any idea what I am missing? It seems like the browser does not actually follow the link.

**Comment by premasagar** [comment]
Just picking up. I hope you got this sorted. I can't think of a reason it wasn't appearing in the Net tab; I would check that the CSS is visible when navigating directly to the URL. Note: on the usage instructions you linked to, note that `http://example.com/cleanslate.css` is just an example URL; you'd have to host your on copy of the CSS file as part of the website you're building and adapt the URL accordingly.
